name: climate_to_energy_conversion

channels:
  - conda-forge

dependencies:
  - python
  - numpy
  - scipy
  - xarray
  - rioxarray
  - netcdf4
  - pandas
  - geopandas
  - openpyxl
  - rasterio
  - shapely
  - cartopy
  - atlite
  - entsoe-py
  - eurostat
  - pytz
  - pip
  - pip:
    - mpi4py
    - dask
    - dask-mpi
    - distributed